# Project Information
site_name: 蓝桥杯备赛文档
site_author: 墨染(MoRan)
site_description: 蓝桥杯备赛历程及知识点整理
site_url: https://saudadestenko.github.io/docs_for_lanqiao/
repo_name: docs_for_lanqiao
repo_url: https://github.com/SaudadesTenko/docs_for_lanqiao
copyright: Copyright © 2022 墨染

# Theme
theme:
  name: 'material'
  language: zh
  icon:
    logo: material/matrix
    edit: material/file-edit-outline
  favicon: assets/favicon.png
  font:
    # 谷歌字体
    text: Ubuntu
    # 等宽字体（用于代码）
    code: Ubuntu Mono
  palette:
    # 浅色模式
    - scheme: default
      # 鼠标 Hover 颜色
      accent: indigo
      # 默认原色
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换到深色模式
    # 深色模式
    - scheme: slate
      # 鼠标 Hover 颜色
      accent: indigo
      # 默认原色
      primary: indigo
      toggle:
        icon: material/weather-night
        name: 切换到灯光模式
  features:
    # 显示编辑此页面按钮
    - content.action.edit
    # 显示查看源代码按钮
    - content.action.view
    # 启用代码注释
    - content.code.annotate
    # 启用代码复制按钮
    - content.code.copy
    # 显示工具提示语
    - content.tooltips
    # 显示页脚中的上一个和下一个按钮
    - navigation.footer
    # 文章顶级标题部分将在侧边栏中呈现，在移动设备上保持为二级目录
    - navigation.sections
    # 显示顶部导航选项卡
    - navigation.tabs
    # 显示返回顶部按钮
    - navigation.top
    # 启用定位点跟踪后，地址栏中的 URL 将使用内容列表中突出显示的活动定位点自动更新
    - navigation.tracking
    # 搜索突出显示
    - search.highlight
    # 启动搜索共享按钮，该按钮允许深层链接到当前搜索查询的结果的具体地址
    - search.share
    # 启用搜索建议，搜索将显示最后一个单词的最可能完成情况，使用右方向键自动补全
    - search.suggest
    # 启用目录锚点跟随
    - toc.follow
  plugins:
    # 搜索
    - search:
      # 增加汉语文本分割库
      jieba_dict: dict.txt
      # 标记器分隔符设置
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  # 覆写文件
  custom_dir: material/.overrides

# 用户自定义加载 CSS
extra_css:
  - stylesheets/extra.css

# 用户自定义加载 JS
extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.js?features=es6
  - https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/mathjax/3.2.0/es5/tex-mml-chtml.js

# 用户其他自定义
extra:
  # 社交链接
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SaudadesTenko
    - icon: logo
      link: https://squidfunk.github.io/mkdocs-material/

# Extensions
markdown_extensions:
  # 启用缩写
  - abbr
  # 启用标注：注意，抽象，信息，提示，成功，问题，警告，失败，危险，错误，例子，告诫
  - admonition
  # 标注功能的增强：使生成的标注可折叠
  - pymdownx.details
  # 启用属性：使用批注，使用网格，添加按钮，添加工具提示，使用带颜色的图标，将图标与动画结合使用，图像对齐，图像延迟加载
  - attr_list
  # 启用脚注
  - footnotes
  # 启用根据此页文章标题级别生成右侧目录
  - toc:
      # 标题的末尾添加锚点
      permalink: ⚓︎
      # 锚点悬停显示名称
      permalink_title: 锚点
  # 启用表格
  - tables
  # 启用渲染块和内联块，集成 MathJax
  - pymdownx.arithmatex:
      generic: true
  # 此扩展允许代码和代码块彼此之间的任意嵌套，包括使用批注，使用代码块，使用内容选项卡等
  - pymdownx.superfences
  # BetterEm 是一个 Python Markdown 扩展的拓展，旨在改善粗体和斜体处理
  - pymdownx.betterem:
      smart_enable: all
  # 插入功能
  - pymdownx.caret
  # 荧光笔标记功能
  - pymdownx.mark
  # 启用 Markdown 删除语法与下标语法
  - pymdownx.tilde
  # 表情符号拓展
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      # 增加代码块语法高亮
  - pymdownx.highlight
  # 增加内联代码块语法高亮
  - pymdownx.inlinehilite
  # 智能符号扩展：添加了用于创建特殊字符（如商标、箭头、分数等）的语法
  - pymdownx.smartsymbols
  # 启用选项卡
  - pymdownx.tabbed:
      alternate_style: true
  # 启用任务列表
  - pymdownx.tasklist:
      custom_checkbox: true

# Contents
nav:
  - 首页: 'index.md'
  - 基础: 'basic.md'
  - 进阶: 'advanced.md'
  - 提高: 'increase.md'
  - 模块: 'module.md'
  - 关于: 'about.md'
